### ISSUE TITLE
Purchasing souvenirs on a trip

### ISSUE THREAD

**Issue by Roger-Chavez** [minorleaguegrayonassociates/GrayonSlam#14]
### Description:
As a Baseball Obsessed fan with deep pockets, I'd like the ability to purchase multiple souvenirs at each location I visit.

### Assumptions:
* The use if able to take a trip
* Classes are made and data is being loaded into he program

### Estimate:
* 5

### Tasks:
- [ ] Create a cart to place items into
- [ ] The receipt must show the number of items bought
- [ ] Have to be able to add or remove items from that cart 
- [ ] Must show a "receipt" after a purchase at each stadium
- [ ] Must also have a grand total receipt that shows all the purchases made at each stadium on the trip with the total amount of money spent at all stadiums

### Tests:
* Test to see the the user is able to add and delete items at each Stadium
* Test to see that when completing a transaction the correct number of items bought displays on the immediate receipt at each restaurant
*  Test to see that when completing a transaction the correct number of items bought displays once the trip is concluded on the grand total receipt for the trip

### Definition of Done:
* The user is able to add items to cart and the user can edit their cart at any point by adjusting the qty, deleting and can add more items to the cart if they wish. 
* The user checks out and the correct item qty show on the immediate receipt and total receipt
